Hello world project
Ibranista/Hello-World pull request #1
Opened 2022-10-25 11:28 UTC by Ibranista

added html file with a heading, having a class of h1. And created a stylesheet for the header (h1) section.

2022-10-25 12:15 UTC, Abenezer-Tilahun requested changes
Hi @Ibranista   , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 👏🏻


✔️ You used correct GitHub Flow.
✔️ Professional README 
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

- [ ]  I recommend that you fix the linters errors in your styles.css. To have the project approved, the linter result should be green. AKA: Linter should report NO errors.
- [ ] Your  Pull Request should have a descriptive title telling you what changes are inside and have a short summary describing introduced changes in more detail.
![Capture](https://user-images.githubusercontent.com/93598189/197770347-c4586b59-6db8-433c-9e60-d0a115939c7e.PNG)

_Check the comments below the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 12:15 UTC, Abenezer-Tilahun commented on hello.css
> +}
- [ ] As stated in the project requirement your .css file should includes one class with styles for your header (make it in your favorite color), Kindly update it.
![Capture](https://user-images.githubusercontent.com/93598189/197765215-b499f339-633e-4a34-a65f-8a5b9bbd5558.PNG)

2022-10-25 12:15 UTC, Abenezer-Tilahun commented on test.md
> +"This file should be ignored by git"
- [ ] - [ ] As stated in the project requirement A test.md file with the text "This file should be ignored by git" is actually ignored by git and is not present in your GitHub repository. but still i see it on your Repo.
![Capture](https://user-images.githubusercontent.com/93598189/197768985-36208f93-4efa-414c-810a-58f5f20fd4fd.PNG)

2022-10-25 12:15 UTC, Abenezer-Tilahun commented on .gitignore
> +.gitignore
- [ ] Please try to remove the .gitingore file .

2022-10-25 13:35 UTC, omarsalem7 requested changes
Hi @Ibranista , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![Almost near](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

 ## Highlights
✔️ All linter checks pass
✔️ Descriptive pull request

 ## Required Changes ♻️
- [ ] Kindly make sure to fix linter errors and make them green by clicking in details and seeing the error and fixing it because it is one of the core requirements.
- [ ] Also consider adding a description for pull request by clicking on 3 dots and then editing the description.
- [ ] _Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-25 13:35 UTC, omarsalem7 commented on .gitignore
> +.gitignore
- [ ] As stated by the previous reviewer, kindly remove `.gitignore` from the `.gitignore` file.

2022-10-26 12:43 UTC, Nemwel-Boniface approved these changes
## Hello @Ibranista      :wave: ,
I am Nemwel your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
Met all the milestone requirements ✔️ 

## [Optional] suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 15:57 UTC, merged